/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Presentacion.Contenido;



import Negocio.Libro;
import Negocio.Libro;
import Datos.Biblioteca;
import Negocio.Documento;
import Negocio.Revista;
import javax.swing.JOptionPane;
import Conexion.*;
import Presentacion.Menu;
/**
 *
 * @author LENOVO
 */
public class IngresarLibro extends javax.swing.JPanel {
   DocumentosRepertorio documentorepertorio=new DocumentosRepertorio();
   
    boolean isEdition = false;
    Documento EditarLibro;
    String id;
    /**
     * Creates new form Libros
     */
    public IngresarLibro() {
        initComponents();
        inicio();

    }
    public IngresarLibro(String id,Documento docu) {
        isEdition = true;
        EditarLibro = docu;
        initComponents();
        inicio();
        this.id=id;
   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtAutor = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        txtEditorial = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtVolumen = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ratSi = new javax.swing.JRadioButton();
        ratNo = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Ingresar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        boxTipo = new javax.swing.JComboBox<>();
        title = new javax.swing.JLabel();
        Ingresar1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(750, 390));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Título :");

        jLabel4.setText("Autor :");

        jLabel5.setText("Editorial :");

        jLabel6.setText("Año :");

        jLabel7.setText("Volumen :");

        jLabel8.setText("Número :");

        jLabel10.setText("Prestamo:");

        ratSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratSiActionPerformed(evt);
            }
        });

        ratNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratNoActionPerformed(evt);
            }
        });

        jLabel11.setText("SI");

        jLabel12.setText("NO");

        jLabel2.setText("Codigo :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(ratSi, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(ratNo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVolumen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ratSi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ratNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAño, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 480, 221));

        Ingresar.setBackground(new java.awt.Color(204, 0, 0));
        Ingresar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        Ingresar.setText("Ingresar");
        Ingresar.setBorderPainted(false);
        Ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ingresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarActionPerformed(evt);
            }
        });
        jPanel1.add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 130, 40));

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 30, 10, 320));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iStock.jpg"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 220, 350));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        jLabel1.setText("Tipo De Documento:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 150, 30));

        boxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Libro", "Revista" }));
        boxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxTipoActionPerformed(evt);
            }
        });
        jPanel1.add(boxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 113, -1));

        title.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        title.setText("Registrar Documentos");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        Ingresar1.setBackground(new java.awt.Color(204, 0, 0));
        Ingresar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Ingresar1.setForeground(new java.awt.Color(255, 255, 255));
        Ingresar1.setText("Regresar");
        Ingresar1.setBorderPainted(false);
        Ingresar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ingresar1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Ingresar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingresar1ActionPerformed(evt);
            }
        });
        jPanel1.add(Ingresar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 130, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inicio(){
            txtAutor.setEnabled(false);
            txtAño.setEnabled(false);
            txtCodigo.setEnabled(false);
            txtEditorial.setEnabled(false);
            txtTitulo.setEnabled(false);
            txtVolumen.setEnabled(false);
            ratNo.setEnabled(false);
            ratSi.setEnabled(false);
            Ingresar.setEnabled(false);
            txtNumero.setEnabled(false);
            if (isEdition) {
            title.setText("Actulizar Libro");
            Ingresar.setText("Modificar");
            }
            if(EditarLibro!=null){
                if (EditarLibro instanceof Revista){
                Revista revi= (Revista) EditarLibro;
                txtVolumen.setText(Integer.toString(revi.getVolumen()));
                txtNumero.setText(Integer.toString(revi.getNumero()));
                txtAutor.setText(revi.getAutor());
                txtAño.setText(Integer.toString(revi.getAnoPub()));
                txtCodigo.setText(revi.getCodigo());
                txtEditorial.setText(revi.getEditorial());
                txtTitulo.setText(revi.getTitulo());
                if(revi.isPrestado()){
                    ratSi.setSelected(true);
                }else{
                    ratNo.setSelected(true);
                }
                boxTipo.setSelectedItem("Revista");
                boxTipo.setEnabled(false);
                txtCodigo.setEditable(false);
                 }else if(EditarLibro instanceof Libro){
                     Libro lib= (Libro) EditarLibro;
                txtVolumen.setEnabled(false);
                txtNumero.setEnabled(false);
                txtAutor.setText(lib.getAutor());
                txtAño.setText(Integer.toString(lib.getAnoPub()));
                txtCodigo.setText(lib.getCodigo());
                txtEditorial.setText(lib.getEditorial());
                txtTitulo.setText(lib.getTitulo());
                if(lib.isPrestado()){
                    ratSi.setSelected(true);
                }else{
                    ratNo.setSelected(true);
                    }
                boxTipo.setSelectedItem("Libro");
                boxTipo.setEnabled(false);
                txtCodigo.setEnabled(false);
                }
            }
    }
    
    private void boxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxTipoActionPerformed
        String opDoc=boxTipo.getSelectedItem().toString();
        if (opDoc.equals("Libro")){
            txtAutor.setEnabled(true);
            txtAño.setEnabled(true);
            txtCodigo.setEnabled(true);
            txtEditorial.setEnabled(true);
            txtTitulo.setEnabled(true);
            txtVolumen.setEnabled(false);
            ratNo.setEnabled(true);
            ratSi.setEnabled(true);
            Ingresar.setEnabled(true);
            txtNumero.setEnabled(false);
        }else if(opDoc.equals("Revista")){
            txtAutor.setEnabled(true);
            txtAño.setEnabled(true);
            txtCodigo.setEnabled(true);
            txtEditorial.setEnabled(true);
            txtTitulo.setEnabled(true);
            txtVolumen.setEnabled(true);
            ratNo.setEnabled(true);
            ratSi.setEnabled(true);
            Ingresar.setEnabled(true);
            txtNumero.setEnabled(true);
        }else{
            txtAutor.setEnabled(false);
            txtAño.setEnabled(false);
            txtCodigo.setEnabled(false);
            txtEditorial.setEnabled(false);
            txtTitulo.setEnabled(false);
            txtVolumen.setEnabled(false);
            ratNo.setEnabled(false);
            ratSi.setEnabled(false);
            Ingresar.setEnabled(false);
            txtNumero.setEnabled(false);
        }
    }//GEN-LAST:event_boxTipoActionPerformed

    private void ratNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratNoActionPerformed
        ratSi.setSelected(false);
    }//GEN-LAST:event_ratNoActionPerformed

    private void ratSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratSiActionPerformed
        ratNo.setSelected(false);
    }//GEN-LAST:event_ratSiActionPerformed

    private void IngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarActionPerformed
        String codigo=txtCodigo.getText();
        String autor=txtAutor.getText();
        String titulo=txtTitulo.getText();
        String editorial=txtEditorial.getText();
        String añoText=txtAño.getText();
        String opDoc=boxTipo.getSelectedItem().toString();
         if (codigo.isEmpty() || autor.isEmpty() || titulo.isEmpty() || editorial.isEmpty() || añoText.isEmpty()) {
        
        JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.");
        return;
    }

    // Verificar que al menos uno de los JRadioButton esté seleccionado
    if (!ratSi.isSelected() && !ratNo.isSelected()) {
        JOptionPane.showMessageDialog(null, "Seleccione al menos una opción para el estado.");
        return;
    }
     int ano=Integer.parseInt(txtAño.getText());
       
     if (opDoc=="Libro"){
            boolean estado;
            if(ratSi.isSelected()==true){
                estado=true;
            }else{
                estado=false;
            }
            Libro li=new Libro(codigo,"Libro",titulo,autor,editorial,ano,estado);
            try {

            if (!isEdition) {
                documentorepertorio.create(li);
            } else {
                documentorepertorio.update(id, li);
            }

            String successMsg = isEdition ? "modificado" : "registrado";

            javax.swing.JOptionPane.showMessageDialog(this, "Libro " + successMsg + " exitosamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            if (!isEdition) {
                limpiarCampos();

            }
        } catch (Exception e) {
            String errorMsg = isEdition ? "modificar" : "registrar";
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " el libro. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }

 
        }else if (opDoc=="Revista"){
            boolean estado;
            if(ratSi.isSelected()==true){
                estado=true;
            }else{
                estado=false;
            }
            int volumen=Integer.parseInt(txtVolumen.getText());
            int numero=Integer.parseInt(txtNumero.getText());
            Revista revi=new Revista(volumen, numero, codigo,"Revista",titulo, autor, editorial, ano, estado);
            try {

            if (!isEdition) {
                documentorepertorio.create(revi);
            } else {
                documentorepertorio.update(id, revi);
            }

            String successMsg = isEdition ? "modificado" : "registrado";

            javax.swing.JOptionPane.showMessageDialog(this, "Libro " + successMsg + " exitosamente.\n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);

            if (!isEdition) {
               limpiarCampos();

            }
        } catch (Exception e) {
            String errorMsg = isEdition ? "modificar" : "registrar";
            javax.swing.JOptionPane.showMessageDialog(this, "Ocurrió un error al " + errorMsg + " el libro. \n", "AVISO", javax.swing.JOptionPane.ERROR_MESSAGE);
            System.out.println(e.getMessage());
        }
     
            
        }
      
    }//GEN-LAST:event_IngresarActionPerformed

    private void Ingresar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingresar1ActionPerformed
        Menu.mostrar(new Books());
    }//GEN-LAST:event_Ingresar1ActionPerformed
 private void limpiarCampos(){
       txtAutor.setText("");
       txtAño.setText("");
       txtCodigo.setText("");
       txtEditorial.setText("");
       txtTitulo.setText("");
       txtVolumen.setText("");
       ratNo.setText("");
       ratSi.setText("");
       txtNumero.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ingresar;
    private javax.swing.JButton Ingresar1;
    private javax.swing.JComboBox<String> boxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton ratNo;
    private javax.swing.JRadioButton ratSi;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEditorial;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtVolumen;
    // End of variables declaration//GEN-END:variables
}
